### ISSUE TITLE
MPI_Wait: Attempting to await unrecognised async request

### ISSUE THREAD

**Issue by n-krueger** [faasm/cpp#37]
Thank you for your work on Faasm, it is really promising!

I am working on porting a few larger MPI codebases to Faasm so that we can compare its performance to existing MPI implementations. Unfortunately I have run into an issue with the following communication pattern:

* `MPI_Irecv` from all other ranks
* `MPI_Send` to all other ranks
* `MPI_Wait` for the `MPI_Irecv` requests

While this works initially, eventually the application will crash with the following message:
`Error: Attempting to await unrecognised async request: 993626942`

I have attached a program that reproduces this behavior: [mpi-irecv-send-example.zip](https://github.com/faasm/cpp/files/6252669/mpi-irecv-send-example.zip)

I am compiling this program inside of the container `faasm/cpp-sysroot:0.0.22` as follows:
```bash
cmake -DCMAKE_TOOLCHAIN_FILE=/usr/local/faasm/toolchain/tools/WasiToolchain.cmake .
cmake --build . --target main --jobs 4
```

I have seen that [MpiWorld::doISendRecv](https://github.com/faasm/faabric/blob/master/src/scheduler/MpiWorld.cpp#L312) uses [faabric::util::generateGid()](https://github.com/faasm/faabric/blob/master/src/util/gids.cpp#L16) to create a request ID. This ID is then used in [MpiWorld::awaitAsyncRequest](https://github.com/faasm/faabric/blob/master/src/scheduler/MpiWorld.cpp#L717) when `MPI_Wait` is called. Is it possible for this ID to repeat, which would cause the same ID to be awaited twice?

**Comment by Shillaker** [comment]
Hi @n-krueger , thanks for raising this. I actually think @csegarragonz fixed this last week, it was a race condition somewhere in the MPI implementation. I think we just need to bump a version here and there and it should be working again. I'll discuss with Carlos and get back to you.

**Comment by n-krueger** [comment]
@Shillaker Thank you for your response. Is this related to this PR: https://github.com/faasm/faabric/pull/67 ?

**Comment by Shillaker** [comment]
It is indeed, that should fix it. I'll be doing another build of Faasm later today or tomorrow which will pick up that change in the relevant container builds, but if you want to rebuild things locally yourself before then then go for it :+1:

**Comment by Shillaker** [comment]
I will also add that our MPI support is currently in the early stages of a research project, and although things may compile and run, I very much doubt the performance will come anywhere close to anything like OpenMPI or MPICH. We're actively working on a paper on the topic, so we'll be doing our own profiling and performance tuning over the next month or two, but in the meantime, it won't be worth the effort if you're looking for something production-ready. However, if you're just interested from a research angle then we should have some interesting results soon.

**Comment by n-krueger** [comment]
That is fine, I am aware that the MPI implementation is not production-ready yet. I am researching how MPI can evolve to enable more use-cases and evaluating Faasm is a part of that. 👍

**Comment by csegarragonz** [comment]
Hi @n-krueger, thanks for pointing this out and using Faasm!

As Simon mentioned, the work with MPI is very much a work in progress. The solution to your particular issue is (hopefully) faasm/faabric#67, please reopen an issue if that's not the case.

Just for reference, the most relevant bits of the implementation are in [faabric](https://github.com/faasm/faabric/tree/master/src/scheduler), but you can see the list of all implemented calls in the WebAssembly stubs [here](https://github.com/faasm/faasm/blob/master/src/wavm/mpi.cpp).

I will close this issue now, but again, reopen if necessary. Lastly, we are happy to review any PR :) A detailed introduction to the development environment is provided in the [docs](https://github.com/faasm/faasm/blob/master/docs/development.md).

**Comment by n-krueger** [comment]
Thank you for the pointers to the relevant information and files. I can confirm that https://github.com/faasm/faabric/pull/67 fixes this bug!
